### ISSUE TITLE
How to contribute with stand-alone rules that aren't part of the Official ruleset?

### ISSUE THREAD

**Issue by toniperic** [friendsoftwig/twigcs#102]
Hello.

In one of my projects, I'm trying to enforce a custom ruleset which would hopefully make templates succinct and readable by a non-technical person, and was curious how I could contribute back here once I'm happy with the setup and once we have all the rules in place. 

I see that there are functional tests which actually test pretty much everything, which are ran against the "Official" ruleset, which is basically just a couple of rules grouped together.  
If I wanted to add new rules and test them, what would be the preferred way to do it with the current setup?  

My understanding is that adding them to the current set/functional test set wouldn't cut it, as they aren't (nor should be) part of the official set, so I'm wondering what do you think would be the best approach to do so?

Now, back onto the custom ruleset – the idea is that a non-technical person should be able to open a template and figure out what is going on.  
To achieve this, there are ground rules in place:

- template must be data-type agnostic -> you should never check if something is exactly `null`, `true` or `false`, because by writing either of those keywords into the template your template is not data-type agnostic anymore
- plain English must be used whenever possible

Following just these two rules arguably made the templates more readable in general (especially to non-technical person), with the extra bonus of having strict comparison in place for free.

## Examples
```twig
{# bad #}
{% if product.price == 100 %}

{# good, plus strict comparison bonus for free #}
{% if product.price is same as (100) %}
```

```twig
{# bad #}
{% if 100 / 5 == 0 %}
{% if 100 / 5 is same as (0) %}

{# good #}
{% if 100 is divisible by (5) %}
```

```twig
{# bad #}
{% if number % 2 == 0 %}
{% if number % 2 is same as (0) %}

{# good #}
{% if number is even %}
```

```twig
{# bad #}
{% if number % 2 == 1 %}
{% if number % 2 is same as (1) %}

{# good #}
{% if number is odd %}
```

Making template data-type agnostic becomes even more obvious when it comes to booleans.

```twig
{# bad #}
{% if user.active is same as (false) %}
{# good #}
{% if not user.active %}

{# bad #}
{% if user.active is same as (true) %}
{# good #}
{% if user.active %}
```

When passing view-models to templating engine (i.e. Twig), they could have optional (i.e. nullable) properties.  
Imagine a template which renders user profile, and among other things their address.

```twig
{# bad – unnecessarily long, breaks the data-type agnostic rule and not so readable, especially to non-technical people #}
{% if user.address is not same as (null) %}
    {{ user.address.zipCode }} {{ user.address.city }}
{% endif %}

{# good #}
{% if user.address %}
    {{ user.address.zipCode }} {{ user.address.city }}
{% endif %}
```

Anyway, there are more of these that I haven't listed, but I'm just wondering about your initial thoughts and the guidelines on how to contribute back.

Maybe there doesn't need to be a new ruleset in place in this repo, but since each of these examples are essentially standalone rules, I would like to contribute back by adding them so people can cherry-pick whichever ones they want into their own rulesets. But then I'm still wondering how to approach the (functional) testing aspect of it?

All constructive feedback and comments are more than welcome. :)

Cheers

**Comment by OwlyCode** [comment]
Hello Toni,

It's an interesting topic and I would be thrilled to support your initiative! I never faced until now the opportunity to add a completely new ruleset. My current take on this would be to create a new repository, like `toniperic/twigcs-<ruleset name>` that contains the ruleset declaration and its custom rules. I see many advantages on this approach :

- This would allow creators to maintain their own ruleset independently, without needing an approval and/or a merge from us.
- This would allow creators to track the popularity of their rulesets on packagist.
- This would prevent to have a lot of rulesets to maintain along twigcs. (they would upgrade asynchronously, and by the hand of their own maintainers)

But there would be work to do on twigcs itself too. At the moment using a custom ruleset only works if twigcs and the ruleset share the same autoloader (that means they are both in the dev-dependencies of the project). I would like to improve this in the future so you can use a ruleset from anywhere on your computer with both installations methods (phar or composer dev-dependency). I'm open to suggestions on that point as I have not started thinking on the technical details of this (autoloading? and where to store the configuration (if any)?).

For the functional testing part, we could create classes to help you do that on your repo. Like Symfony having a `KernelTestCase` and a `CommandTester` class. For instance :

```php
use FriendsOfTwig\Twigcs\RulesetTestCase;

class FunctionalTest extends RulesetTestCase
{
    public function testMyRules()
    {
        $this->assertTwigcsValidFiles(__DIR__ . '/../data/corpus');
        $this->assertTwigcsValid('{{ foo }}');
        $this->assertTwigcsInvalid('{{ foo  }}', 'Hey there is an extra space here!', 'error', [1, 7]);
    }
}
```

What do you think about this ?

**Comment by toniperic** [comment]
Hey Tristan, sorry for the late reply.

That sounds good, thanks for the advice.

Regarding the autoloading part - that's not something I've tackled yet as my ruleset and TwigCS **do** share the same autoloader, so I don't have any suggestions at the moment, sorry. I'll for sure get back to you if something pops up.

As for the testing utilities - that could be a nice enhancement, yeah. Anything that would streamline testing definitely has a thumbs up from me.

**Comment by OwlyCode** [comment]
Closing this as #148 allows to have custom rulesets :)
