### ISSUE TITLE
Packagist doesn't have latest releases

### ISSUE THREAD

**Issue by yguedidi** [friendsoftwig/twigcs#103]
It misses the v3.2.2 and v4.0-BETA3, and dev-master points to commit d6a9cdf35c97c857104f6e764866e302aa463520 instead of 80d4f9a3b83bd413a7ff0561dd0b145d18e1220e

**Comment by OwlyCode** [comment]
Hello there, good catch! It's fixed now.

**Comment by yguedidi** [comment]
@OwlyCode this seems to be the case again, master is 53be26af27fa8dd59a6794ac421e931ddb6ffd54 on GitHub but dev-master on Packagist is acfe6de29b4c3a6c75994a586c660cf58c60f744.
Many you should configure automatic updates on packagist so this never happen again?

**Comment by OwlyCode** [comment]
@yguedidi I think I found the problem. Old settings from the previous organization were still set. I changed them and triggered an update.
