### ISSUE TITLE
Maximum function nesting level reached

### ISSUE THREAD

**Issue by toniperic** [friendsoftwig/twigcs#109]
FWIW I've got xdebug `2.8.0`, but I don't think this issue is specific to that version.

This is the ruleset in place:

```php
$configurator = new RulesetConfigurator();
$builder = new RulesetBuilder($configurator);

$configurator->setTagSpacingPattern('{% expr %}');
$configurator->setPrintStatementSpacingPattern('{{ expr }}');
$configurator->setEmptyParenthesesSpacingPattern('()');
$configurator->setParenthesesSpacingPattern('(expr)');
$configurator->setListSpacingPattern('expr, expr');
$configurator->setArraySpacingPattern('[expr]');
$configurator->setEmptyArraySpacingPattern('[]');
$configurator->setHashSpacingPattern('{key: expr, key: expr}');
$configurator->setEmptyHashSpacingPattern('{}');
$configurator->setUnaryOpSpacingPattern('op expr');
$configurator->setBinaryOpSpacingPattern('expr op expr');
$configurator->setRangeOpSpacingPattern('expr..expr');
$configurator->setTernarySpacingPattern('expr ? expr : expr||expr ?: expr');

return [
    new Rule\RegEngineRule(Violation::SEVERITY_ERROR, $builder->build()),
];
```

And this is the template:
```twig
{% set
    map = {
        a: 'a',
        b: 'b',
        c: 'c',
        d: 'd',
        e: 'e',
        f: 'f',
        g: 'g',
        h: 'h',
        i: 'i',
        j: 'j',
        k: 'k',
        l: 'l',
        m: 'm',
        n: 'n',
        o: 'o',
        p: 'p',
        r: 'r'
    }
%}
```

The output is
> PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting!

If I omit just one element from the map, like so:

```twig
{% set
    map = {
        a: 'a',
        b: 'b',
        c: 'c',
        d: 'd',
        e: 'e',
        f: 'f',
        g: 'g',
        h: 'h',
        i: 'i',
        j: 'j',
        k: 'k',
        l: 'l',
        m: 'm',
        n: 'n',
        o: 'o',
        p: 'p'
    }
%}
```

Then the output is:
```
l.1 c.6 : ERROR There should be 1 space after the "set".
1 violation(s) found
```

Additionally, if I don't omit any items, but change the indentation, like so:
```twig
{% set
map = {
    a: 'a',
    b: 'b',
    c: 'c',
    d: 'd',
    e: 'e',
    f: 'f',
    g: 'g',
    h: 'h',
    i: 'i',
    j: 'j',
    k: 'k',
    l: 'l',
    m: 'm',
    n: 'n',
    o: 'o',
    p: 'p',
    r: 'r'
}
%}
```

then the output is:
> No violation found.

In addition, if I run the script with `xdebug.max_nesting_level=300`, then the fatal error will not occur.

**Comment by OwlyCode** [comment]
This is a problem because it will force xdebug users to tweak their max nesting level when they probably use it on other projects as a safe guard on complexity. I use a lot of recursivity in the new version and that is what breaks the limit.

For the time being maybe we can go with `php -d xdebug.max_nesting_level=300 twigcs [...]` as a suggested workaround?

**Comment by toniperic** [comment]
Yeah, I agree that's an option.

Additional solution would also be to just disable xdebug altogether.

After re-considering this, I propose we close the issue for now, as this is something that happens only when the xdebug extension is installed and enabled, and not something that necessarily has to do with PHP or the library itself.
