### ISSUE TITLE
Disable rules via CLI option?

### ISSUE THREAD

**Issue by chasegiunta** [friendsoftwig/twigcs#110]
I'm unable to figure out how to load a custom ruleset within the context of my global composer instance. I'm unsure where to place the file, exactly how to get `composer` to see the file, how to reference it, etc.

Is it possible that there could be a way to disable specific rules via the command line?

I'm using twigcs within Craft CMS, and pascalCase is commonly used throughout our code for variable naming, and even Craft's internal templating, thus the `LowerCaseVariable` is a rule we'd like to exclude.

**Comment by OwlyCode** [comment]
Hello,

Concerning the ability to disable a rule with CLI option, it's not possible, and I don't think it would be that useful in comparison of custom rulesets.

At the moment it is only possible to use a custom ruleset when twigcs and the ruleset share the same autoloader. This leaves two options :

- Adding twigcs as a dependency of your project and the ruleset class in the sources.
- Making a package of your ruleset and install it globally.

I would like to improve on that in the future but I've not yet asked the newly formed community about what they'd want to see.

**Comment by dima-alekseev** [comment]
Possible solution with custom RulesetBuilder:
```php
<?php
// Official.php

namespace FriendsOfTwig\Twigcs\Ruleset;

use FriendsOfTwig\Twigcs\RegEngine\RulesetBuilder;
use FriendsOfTwig\Twigcs\RegEngine\RulesetConfigurator;
use FriendsOfTwig\Twigcs\Rule;
use FriendsOfTwig\Twigcs\Validator\Violation;

/**
 * Custom twigcs ruleset, based on
 * dev/vendor/friendsoftwig/twigcs/src/Ruleset/Official.php
 *
 * @author dalekseev
 */
class Official implements RulesetInterface {

  /**
   * {@inheritdoc}
   */
  public function getRules() {

    $configurator = new RulesetConfigurator();
    $config = $configurator->getProcessedConfiguration();
    $builder = new RulesetBuilder($configurator);
    $ruleset = $builder->build();

    /*
     * Allows set statement to start on next line (drupal 8 twig style):
     * {%
     *   set classes = [
     *     'node',
     *     'node--type-' ~ node.bundle|clean_class,
     *     node.isPromoted() ? 'node--promoted',
     *     node.isSticky() ? 'node--sticky',
     *     not node.isPublished() ? 'node--unpublished',
     *     view_mode ? 'node--view-mode-' ~ view_mode|clean_class,
     *   ]
     * %}
     */
    foreach ($ruleset['expr'] as $key => $item) {
      if ($item && $item[1] && $item[1] == '<➀set➊@➋=➌$➁>') {
        $newSetRule['expr'][$key] = [
          $item[0],
          $item[1],
          $builder
            ->handle()
            ->enforceSpaceOrLineBreak('➀', $config['tag']['before'], 'A tag statement should start with %quantity% space(s).')
            ->enforceSpaceOrLineBreak('➁', $config['tag']['after'], 'A tag statement should end with %quantity% space(s).')
            ->delegate('$', 'expr')
            ->enforceSize('➊', $config['set']['after_set'], 'There should be %quantity% space(s) after the "set".')
            ->enforceSize('➋', $config['set']['after_var_name'], 'There should be %quantity% space(s) before the "=".')
            ->enforceSize('➌', $config['set']['after_equal'], 'There should be %quantity% space(s) after the "=".'),
        ];
        break;
      }
    }
    $new_ruleset = $newSetRule ? array_replace_recursive($ruleset, $newSetRule) : $ruleset;

    return [
      new Rule\LowerCaseVariable(Violation::SEVERITY_ERROR),
      new Rule\RegEngineRule(Violation::SEVERITY_ERROR, $new_ruleset),
      new Rule\TrailingSpace(Violation::SEVERITY_ERROR),
      new Rule\UnusedMacro(Violation::SEVERITY_WARNING),
      new Rule\UnusedVariable(Violation::SEVERITY_WARNING),
    ];
  }
}
```

Just put into your composer.json the follows to use it:
```javascript
    "autoload": {
        "files": [
            "src/Ruleset/Official.php"
        ]
    },
```

**Comment by Yivan** [comment]
@chasegiunta I would like having this cli options to (i use phar).
For now a solution if you use phar is relying on the output result and combine grep/sed to exclude rules. Example to exclude sapce before after pipe and lower case rule:

```
php twigcs.phar path/to/folder | (! grep -v '|' ) | (! grep -v 'lower case' ) | sed '/\.twig/{$!N;/\n.*\.twig/!P;D}' | sed '/\.twig/{$!N;/\n.* found/!P;D}' | (! grep -v 'violation(s) found' )
```

If output is empty no errors, instead errors.
It is somehow hacky, and not not usable by IDE, but for CI or precommit hook, it can do the job.

**Comment by OwlyCode** [comment]
Closing this as we can now have file based configuration with ability to use custom rulesets on a per-file basis. (see #148)
