### ISSUE TITLE
Error filter function

### ISSUE THREAD

**Issue by oliverfg** [friendsoftwig/twigcs#111]
Hello,

I'm using the v3.2.2 twigcs library and i think find a problem. 

For example:
`{% set sizes = [34, 36, 38, 40, 42] %}`
`{{ sizes|filter(v => v > 38)|join(', ') }}`

When execute twigcs i receive the following error:

> ERROR There should be 1 space(s) before ">".

Obviously I can't separate the characters ( => ) because otherwise I get twig error.

**Comment by OwlyCode** [comment]
Hello,

Arrow functions support was added in `4.0-BETA`. If you do not use custom rulesets there is very little pain upgrading to the beta.

I can't add it (by lack of time) to the `3.2` branch as it would require a lot of time to add a new feature on a version that won't be supported in the long run.

**Comment by oliverfg** [comment]
Hello,

Thanks very much for the feedback. I'll use the 4.0-BETA
