### ISSUE TITLE
False/positive for ternary operator inside array

### ISSUE THREAD

**Issue by dima-alekseev** [friendsoftwig/twigcs#122]
Got this error
`ERROR There should be 1 space between the "%" operator and its left operand.`
for the following template:
```twig
{% set interval = [view_mode ? 'paragraph--view-mode--'] %}
{{ interval }}
```
But this is a correct code according the twig official examples (see third line) - https://twig.symfony.com/doc/3.x/templates.html#other-operators

* ?:: The ternary operator:
```twig
{{ foo ? 'yes' : 'no' }} 
{{ foo ?: 'no' }} is the same as {{ foo ? foo : 'no' }} 
{{ foo ? 'yes' }} is the same as {{ foo ? 'yes' : '' }}
```

**Comment by dima-alekseev** [comment]
One more affected template:
```twig
{% set classes = [
    'paragraph',
    'paragraph--type--' ~ paragraph.bundle|clean_class,
    view_mode ? 'paragraph--view-mode--' ~ view_mode|clean_class,
    not paragraph.isPublished() ? 'paragraph--unpublished'
  ] %}
```

**Comment by OwlyCode** [comment]
I tried your templates on the last version (4.0-BETA3) and could not reproduce the problem. I guess you are using the 3.x version. We brought a lot of fixes and improvements for handling ternaries in the beta. If you are not using any custom ruleset I strongly encourage you to move to the 4.0-BETA3 which is really stable.

Edit: Fixed wrong beta number in my answer
