### ISSUE TITLE
Fatal error: Class 'FriendsOfTwig\Twigcs\TwigPort\Error' not found in/friendsoftwig/twigcs/src/TwigPort/SyntaxError.php on line 12

### ISSUE THREAD

**Issue by Boegie** [friendsoftwig/twigcs#124]
Looks like the Error Class from `twigphp/Twig` (https://github.com/twigphp/Twig/blob/3.x/src/Error/Error.php) hasn't made it into the TwigPort directory.

So now `src/TwigPort/SyntaxError.php` is extending a non-existing class.

**Comment by Boegie** [comment]
`~/.composer/vendor/bin/twigcs --twig-version 1 .` was used to stumble on this error (and a faulty Twig file)

**Comment by Boegie** [comment]
Briefly looked into adding https://github.com/twigphp/Twig/blob/3.x/src/Error/Error.php, but that depends on https://github.com/twigphp/Twig/blob/3.x/src/Template.php which pulls in a ton of dependencies for Twig.

**Comment by OwlyCode** [comment]
Thank you for spotting this. I'll come with a solution.

**Comment by OwlyCode** [comment]
All credits goes to @laurentmuller who fixed this :)
