### ISSUE TITLE
[Bug/Doc] No display options, nor severity notice

### ISSUE THREAD

**Issue by Yivan** [friendsoftwig/twigcs#126]
Hello,

Just trying the phar version (last stable, not the prerelease one), i got error because display option is not available nor the severity level.
Is it a bug or doc should be adapted ?

Thanks

P.S: how do I filter to only have error displayed and having a retrun code different on 0 juste for errors. Thanks!

**Comment by Yivan** [comment]
Severity level seems not to work too... The help says:
`-s, --severity=SEVERITY  The maximum allowed error level. [default: "warning"]``

If I set `--severity=error`, wanring are always displayd (i tested my chance with warning but they are deisplayed too). I think related to the missing `display` option.

EDIT: i confirm by setting warning as level, warning are reported but error code is 0 (all ok). So this is fine it seems.

**Comment by OwlyCode** [comment]
Hello!

The display option was introduced recently by #125 and is only inside master at the moment. It will make it into the next beta when #115 is ready.

There is still the severity filter in older versions that works as you mentioned. By the way, I strongly recommend you use the latest beta as it is way more stable than the older release and also contains a lot of bugfixes that were not possible with the old code architecture. It is completely transparent to upgrade if you have no custom rulesets.

**Comment by Yivan** [comment]
@OwlyCode Thanks for your return !

I will give a try to the beta so.
This is sure that the beta is more "stable" than the stable version ? I prefer to ask again sorry as it is to use in a CI pipeline on our servers for production quality before releasing our projects.

**Comment by OwlyCode** [comment]
I can confirm you it is. It handles way more things that were not doable with the old code. Also, the testsuite is the same so there are no regressions on what is covered and the known bugs.
