### ISSUE TITLE
[Beta - Bug] Rule hash

### ISSUE THREAD

**Issue by Yivan** [friendsoftwig/twigcs#127]
Hello,

I just try the latest beta at this day, and i got for:

```
{{ pimcore_image('image', { thumbnail: 'galleryThumbnail', class: 'img-thumbnail'}) }}
```

the message: `ERROR There should be 0 space before the hash values`.
Twigcs want:
`{{ pimcore_image('image',{ thumbnail: 'galleryThumbnail', class: 'img-thumbnail'}) }}`

I don't think it is covered by the twig code standart, so it should be left as it is without any message.
Or at least allow 1 space (which for me is the good way, like php way, and improve lisibility).

Thanks!

**Comment by OwlyCode** [comment]
I'm afraid there is a misunderstanding here, it's not before the `{` that the space is expected but before the values list : 

```
Wrong
{{ pimcore_image('image',{ thumbnail: 'galleryThumbnail', class: 'img-thumbnail'}) }}

Good
{{ pimcore_image('image', {thumbnail: 'galleryThumbnail', class: 'img-thumbnail'}) }}
```

This rule follows https://twig.symfony.com/doc/3.x/coding_standards.html : 

![image](https://user-images.githubusercontent.com/1631270/74740653-97c51a80-525b-11ea-8090-9650453935ad.png)

**Comment by Yivan** [comment]
Ho yes really sorry, i have to read more the message! You can close this issue, all is ok.
