### ISSUE TITLE
Roadmap for the 4.0 stable release

### ISSUE THREAD

**Issue by stof** [friendsoftwig/twigcs#134]
Do you have any estimate for when a stable release of 4.0 will happen ?

**Comment by OwlyCode** [comment]
Hello,

Sadly no. I managed to get some work time for the project at the beginning of 2020 but the COVID19 and its economic effects have engulfed all of it.

I'll gather a list of issues and BC breaks that need to go in the 4.0 and build a milestone before the end of the week.

**Comment by OwlyCode** [comment]
So I took some time and fixed/merged some things. Here's a list of blocking issues before the 4.0 is out: https://github.com/friendsoftwig/twigcs/issues?q=is%3Aopen+is%3Aissue+milestone%3A4.0.0

**Comment by OwlyCode** [comment]
Twigcs 4.0.0 is now released: https://github.com/friendsoftwig/twigcs/releases/tag/v4.0.0
