### ISSUE TITLE
Not possible to use ** in templates

### ISSUE THREAD

**Issue by a-menshchikov** [friendsoftwig/twigcs#135]
When I try to use `**` operator, twigcs write an error:

> ERROR There should be 1 space between the "*" operator and its right operand.

**Comment by OwlyCode** [comment]
I confirm the issue on the master branch. Thank you for reporting this!

**Comment by Dodenis** [comment]
Fix in this PR #143

**Comment by OwlyCode** [comment]
The fix has been merged, thank you everyone for your help!
