### ISSUE TITLE
How to break long lines according to the coding standard?

### ISSUE THREAD

**Issue by SimonHeimberg** [friendsoftwig/twigcs#140]
When I break long lines in twig, I do it like this:
```twig
...
    {% if some_var.getA().hasB() and other_var.hasAllValuesSet() and
        other_var.allIsReady() and app.user and app.user.getGroups()
    %}
        {{ some_var }}
    {% endif %}
...
```
But twigcs reports there shall not be multiple spaces before `%}` (or `}}` or `#}`).

Suggestion: Either recommend some other style, or allow spaces when on a new line (`'^ *%}'`).

The twig coding standard does not mention breaking long lines.

This is similar as breaking long conditions in https://www.php-fig.org/psr/psr-12/#51-if-elseif-else .

**Comment by OwlyCode** [comment]
Hello and sorry for the long delay answering this. I find it hard to allow new lines before and after delimiters because this would allow them anywhere. Like this:

```twig
{%
    block example %}

{% endblock
%}
```

To me the right approach to this is to shorten your condition, for instance by using temporary variables:

```twig
{% set hasBOrEveryting = some_var.getA().hasB() and other_var.hasAllValuesSet() %}
{% set isReadyOrHasGroups = other_var.allIsReady() and app.user and app.user.getGroups() %}

{% if hasBAndEveryting and isReadyAndHasGroups %}
    {{ some_var }}
{% endif %}
```

**Comment by OwlyCode** [comment]
Closing this as you can now use your own ruleset with a config file. (see #148)
