### ISSUE TITLE
Unexpected warnings and errors in v4

### ISSUE THREAD

**Issue by duboiss** [friendsoftwig/twigcs#155]
I am surprised to get new warnings and errors with TwigCs 4. I didn't use yet the new TwigCs configuration file.

```
v4.0-BETA4
 ᨂ twigcs templates
No violation found.
```

```
v4.0
 ᨂ twigcs templates
templates/thread/show.html.twig
l.43 c.23 : WARNING Unused variable "part".
l.52 c.23 : WARNING Unused variable "message".
templates/thread/new.html.twig
l.12 c.11 : WARNING Unused variable "part".
templates/forum/show.html.twig
l.18 c.23 : WARNING Unused variable "part".
templates/forum/category.html.twig
l.21 c.15 : WARNING Unused variable "forum".
templates/message/edit.html.twig
l.13 c.11 : WARNING Unused variable "part".
templates/pages/forums.html.twig
l.22 c.31 : WARNING Unused variable "forum".
templates/partials/_pagination.html.twig
l.3 c.113 : ERROR There should be 0 space before the "=" in the named arguments list.
l.4 c.99 : ERROR There should be 0 space before the "=" in the named arguments list.
```

**For the 7 warnings, some reveal of this behaviour.**
I include a twig file in a for. I use directly the variable (message here) in the included file.
```twig
{% for message in pagination %}
    {{ include('message/_message_card.html.twig', {displayActions: true}) }}
{% endfor %}
```
It is not mandatory to pass the variable manually since the file is included. It's like a PHP include.

For others, it's very simple.
I have this kind of code in several templates to manage my breadcrumb.
```twig
{% for part in forum|breadcrumb %}
    {% do append_breadcrumb(part.url, part.title) %}
{% endfor %}
```
Because the variable is not displayed but passed to a function, I have the warning.

**Next, for the errors.**
I need to replace
```twig
{% set class_align = (align is not defined) ? '' : align == 'center' ? ' justify-content-center' : (align == 'right' ? ' justify-content-end' : '') %}
{% set class_size = (size is not defined) ? '' : size == 'large' ? ' pagination-lg' : (size == 'small' ? ' pagination-sm' : '') %}
```
by
```twig
{% set class_align = (align is not defined) ? '' : align == 'center' ? ' justify-content-center' : (align== 'right' ? ' justify-content-end' : '') %}
{% set class_size = (size is not defined) ? '' : size == 'large' ? ' pagination-lg' : (size== 'small' ? ' pagination-sm' : '') %}
```
So remove the space before the comparison in the parentheses. I guess it's related to #149 in `src/RegEngine/RulesetBuilder.php ` [line 589](https://github.com/friendsoftwig/twigcs/pull/149/commits/9ea9698812de31ff3c87e83fabdb6c46fc43ce60#diff-b8de2b0b5e19660085162281ef8eb62c5f9496c2438f23d2895854b26e4cef12R589)

Of course, I don't think this is normal given the first comparison which preserves the space between and after the operator.
align == 'center' and align== 'right'

**Comment by Ciloe** [comment]
For the errors here 
```
templates/partials/_pagination.html.twig
l.3 c.113 : ERROR There should be 0 space before the "=" in the named arguments list.
l.4 c.99 : ERROR There should be 0 space before the "=" in the named arguments list.
```

It's because the conditions `==` are in parenthesis. So we need to change a rule.

For the others errors about unused variables it's a big project we need to work on. See #121.

Thank you !
