### ISSUE TITLE
Unused variable within for loop

### ISSUE THREAD

**Issue by Proxxx23** [friendsoftwig/twigcs#166]
Hello,

I have problem with iterating over array elements while not using every element. Sample code:

```
{% for page in pages %}
  {% include '@plugins/ewconcepts/src/templates/admin/page-row.twig' %}
{% endfor %}
```

I get:
l.174 c.27 : WARNING Unused variable "page".

Is there any way to go through it?

**Comment by Ciloe** [comment]
Yes, it's a global problem about using variables checker. See #121

**Comment by Proxxx23** [comment]
> Yes, it's a global problem about using variables checker. See #121

Oh, okay, I understand. Thanks!

**Comment by OwlyCode** [comment]
Thank you for submitting the issue. I'm closing this as duplicate in favor of #121
