### ISSUE TITLE
General question about fix

### ISSUE THREAD

**Issue by MockingMagician** [friendsoftwig/twigcs#173]
Hello guys, girls,

Your project looks great!

I didn't find a command that allows to fix the files directly like with phpcs. Did I search wrong? Is it under development ? Or simply not on the agenda?

Command example : `twigcs fix path/to/views`

**Comment by Ciloe** [comment]
No, we haven't fixer. It's a very big development and we haven't time to do. If you want you can add this feature ! 

I started to develop an Intelij plugin to have notifications in PHPStorm, and maybe have a fixer, but time is hard to have....

**Comment by MockingMagician** [comment]
Yeah sure, I understand, in any case thanks for feedback.

**Comment by noniagriconomie** [comment]
@MockingMagician there is https://github.com/VincentLanglet/Twig-CS-Fixer I found recently
