### ISSUE TITLE
If with parentheses handling

### ISSUE THREAD

**Issue by denisvmedia** [friendsoftwig/twigcs#179]
I'd like to be strict about parentheses used in ifs. Here is an example of what I'd like to avoid:

```
{% if(entity.property is not empty and entity.property2 is not empty) %}
```

Note that there is no space and there are excessive parentheses. So, I'd like to force it to look like this:

```
{% if entity.property is not empty and entity.property2 is not empty %}
```

Should I create my custom code style? Or could it be a part of the bundled standards? Thanks.

**Comment by denisvmedia** [comment]
@OwlyCode ping :)

**Comment by OwlyCode** [comment]
Hi, and sorry for the long, long time before answering you.

I reviewed the [coding standards of twig](https://twig.symfony.com/doc/3.x/coding_standards.html) and there is no mention that parenthesis are mandatory or forbidden. My guess about that is that the official ruleset should allow both (with one space). If you want to forbid them, you'd have to create your own ruleset.
