### ISSUE TITLE
Sign PHAR releases

### ISSUE THREAD

**Issue by prudloff-insite** [friendsoftwig/twigcs#182]
We install tools on our CI with [phive](https://phar.io/).
This allows downloading PHAR files and checking their signature automatically.
However, it requires that PHAR files come with a signature that is used to verify the PHAR.

Would it be possible to [provide signatures](https://phar.io/howto/sign-and-upload-to-github.html) for twigcs PHAR files?

**Comment by OwlyCode** [comment]
Hi,

Yes it is, I will ping you here when it's ready.

**Comment by OwlyCode** [comment]
@prudloff-insite the latest release of twigcs has been signed. Please let me know if you encounter any issue with it. Thank you for your patience!
