### ISSUE TITLE
Ability to exclude files (not only dirs) and/or limit sniffing to git diff

### ISSUE THREAD

**Issue by jklmnop** [friendsoftwig/twigcs#183]
We have a GrumPHP setup with a TwigCS task and although it works really well, TwigCS is blocking every commit because it's sniffing and failing on files that haven't changed.

When trying to patch the GrumPHP TwigCS task issue myself, I noticed that TwigCS is only using the `exclude` method of Symfony's Finder class, but it does not leverage the `notPath` method. Apparently, `exclude` is only able to handle directories, whereas `notPath` can handle both.

When I changed the calls from `exclude` to `notPath` I was immediately able to exclude both directories and files. 

https://github.com/friendsoftwig/twigcs/blob/fbb854ca7fbfe5862fcdc584ffe61f40e11dd5ea/src/Config/ConfigResolver.php#L294

https://github.com/friendsoftwig/twigcs/blob/fbb854ca7fbfe5862fcdc584ffe61f40e11dd5ea/src/Config/ConfigResolver.php#L298

With regards to allowing checking stdIn (for git diff), that's above my head. But if PHPCS can do it, so could TwigCS.

Anyway, this would be a great feature for a great piece of software. Thanks for all your hard work!

**Comment by OwlyCode** [comment]
Closed by #184
