### ISSUE TITLE
Please publish the new release (for symfony 6 use)

### ISSUE THREAD

**Issue by bastien70** [friendsoftwig/twigcs#192]
You updated the **composer.json** allowing Symfony 6.0 :

```json
    "require": {
        "php": "^7.4 || ^8.0",
        "symfony/console": "^4.4 || ^5.3 || ^6.0",
        "symfony/finder": "^4.4 || ^5.3 || ^6.0",
        "symfony/filesystem": "^4.4 || ^5.3 || ^6.0"
    },
```

But you haven't done the release. We therefore cannot update our projects using Symfony to version 6 until you release your changes.

**Comment by duboiss** [comment]
If you can't wait, use the `dev-master` version.
`composer req --dev friendsoftwig/twigcs:dev-master`

**Comment by OwlyCode** [comment]
I'm sorry it took so long, but this is published now!
