### ISSUE TITLE
Support config files with `.php` extension

### ISSUE THREAD

**Issue by yguedidi** [friendsoftwig/twigcs#246]
In addition to the already supported `.twig_cs` and `.twig_cs.dist` files, I suggest to add the support for `.twig_cs.php` and `.twig_cs.dist.php`
Inspired from PHP-CS-Fixer, they already did that in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5607, they also have removed the support of old names in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5609

Benefits of this move are:
- IDE will automatically detect the file as being a PHP file
- the config file can be targeted in a generic way with `*.php` like other PHP files to be included in other CS tools like PHP-CS-Fixer, PHP_CodeSniffer, etc, no need to maintain it as a particular case

I can try to come with a PR if the idea is accepted

**Comment by localheinz** [comment]
@yguedidi 

Sounds like a good improvement to me!
