### ISSUE TITLE
Unused macro checker does not handle scopes properly

### ISSUE THREAD

**Issue by stof** [friendsoftwig/twigcs#27]
The body of a macro is a fully isolated scope. So an import done inside a macro must be checked for usage only inside the macro. And an import done outside the macro must look for usages outside the macro too (finding a usage inside the macro is not valid, as it cannot reference the macro).
And the implementation must be careful that the same name can be used inside and outside the macro.

**Comment by OwlyCode** [comment]
This should be fixed by https://github.com/allocine/twigcs/pull/44
