### ISSUE TITLE
Detection of macros badly assumes import as being reserved

### ISSUE THREAD

**Issue by stof** [friendsoftwig/twigcs#28]
The detection of macro assumes than any `import` name token involves a macro import. but this is wrong. `import` can be used as a variable name, a function name (and even a macro name), which are all name tokens too.

Instead, the code should look for a `{% import` or `{% from ... import` combination (`{%` is a `BLOCK_START_TYPE` token).

**Comment by stof** [comment]
Note that I haven't reviewed other rules. they might be affected too. I discovered this for UnusedMacro because I look at the implementation when reviewing #24.

**Comment by OwlyCode** [comment]
This is fixed by https://github.com/allocine/twigcs/pull/44
