### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by rajeshreeputra** [friendsoftwig/twigcs#295]
#### Steps required to reproduce the problem

1. Be on PHP 8.3
2. `composer require friendsoftwig/twigcs`

#### Expected Result
- It should be compatible with PHP 8.3

#### Actual Result
- friendsoftwig/twigcs is locked to version 6.2.0 and an update of this package was not requested.
- friendsoftwig/twigcs 6.2.0 requires php ~8.0.0 || ~8.1.0 || ~8.2.0 -> your php version (8.3.0-dev) does not satisfy that requirement.

**Comment by rajeshreeputra** [comment]
I have created PR https://github.com/friendsoftwig/twigcs/pull/296 to support PHP 8.3.
Tested Locally and looks good. Please review.

**Comment by Ciloe** [comment]
Good for me. Thanks !

**Comment by OwlyCode** [comment]
Solved by #296
