### ISSUE TITLE
Release for the PHP 8.3 support

### ISSUE THREAD

**Issue by stof** [friendsoftwig/twigcs#305]
The latest release does not support PHP 8.3.

The dev version already supports it thanks to https://github.com/friendsoftwig/twigcs/pull/296
As PHP 8.3.0 has been release, it would be great to tag a new release of this package.

**Comment by localheinz** [comment]
Released as [`friendsoftwig/twigcs:6.3.0`](https://github.com/friendsoftwig/twigcs/releases/tag/6.3.0).

**Comment by stof** [comment]
thanks
