### ISSUE TITLE
errorformat for vim's syntastic

### ISSUE THREAD

**Issue by jwmwalrus** [friendsoftwig/twigcs#38]
Hi.

I'm trying to make twigcs work with vim's syntastic.  Although I had no problem adding the syntax checker, syntastic requires every warning/error line reported to include the file name.

twigcs' output only shows the file name right before the list of errors for that particular file. Is there any way to change that behavior to include the file name at the beginning of every warning/error reported?

**Comment by OwlyCode** [comment]
Hi !

I guess you could write a custom reporter (could be named SyntasticReporter) here : https://github.com/allocine/twigcs/tree/master/src/Reporter

Check the code of `ConsoleReporter` it should be a great source of inspiration ! And if you do write it, open a PR ;)

**Comment by Ciloe** [comment]
Hi @jwmwalrus, can you show an exemple of report that you want ?

**Comment by Ciloe** [comment]
I used the `ecmas` reporter. The pull request is launch

**Comment by Ciloe** [comment]
@OwlyCode this issue can be close, see https://github.com/vim-syntastic/syntastic/commit/63741646a9e87bbe105674747555aded6f52c490
