### ISSUE TITLE
Twig 1 support

### ISSUE THREAD

**Issue by Chi-teck** [friendsoftwig/twigcs#43]
According to requirements in _composer.json_ Twics should be compatible with Twig 1 but it's not.
`PHP Fatal error:  Declaration of Allocine\Twigcs\Compatibility\TwigLexer::tokenize(Twig_Source $source) must be compatible with Twig_Lexer::tokenize($code, $name = NULL) in /var/www/rocketsoftware/vendor/allocine/twigcs/src/Compatibility/TwigLexer.php on line 28`

**Comment by OwlyCode** [comment]
Hey there, the problem has been solved in 3.1.2 : https://github.com/allocine/twigcs/releases/tag/v3.1.2

**Comment by erik-seifert** [comment]
Seems not be working.
twig/twig : 1.38.3
allocine/twigcs: 3.1.3

**Comment by erik-seifert** [comment]
Declaration of Allocine\Twigcs\Compatibility\TwigLexer::tokenize(Twig_Source $source) must be compatible with Twig\Lexer::tokenize($code, $name = NULL)

**Comment by Chi-teck** [comment]
There were a couple regressions recently in Twig project. Updating the latest Twig 1 release resolved the issue for me.
