### ISSUE TITLE
Variable usage not detected when using include as a function

### ISSUE THREAD

**Issue by OwlyCode** [friendsoftwig/twigcs#49]
When using the following snippet :

```twig
{% set icon %}
    {{ block('svg_icon') }}
{% endset %}

{{ include('@WebProfiler/Profiler/toolbar_item.html.twig', { link: true, icon: icon }) }}
```

A false positive is generated : `WARNING Unused variable "icon".`

**Comment by Chi-teck** [comment]
I think it has nothing to do with `include`. The following Twig code produces the same warning.
```twig
{% set foo %}bar{% endset %}
{{ foo }}
```

**Comment by OwlyCode** [comment]
Yes, it was related to the `{% set foo%} ... {% endset %}`. Twigcs was searching for a `=` in `{% set foo %}`, which it did not find and skipped whole parts of the code. I fixed this in https://github.com/allocine/twigcs/pull/52 so that the lookup for the `=` ends at the end of the block `%}`.

**Comment by OwlyCode** [comment]
Fixed !
