### ISSUE TITLE
When the path argument is given with a trailing slash, it is propagated to the output

### ISSUE THREAD

**Issue by alister** [friendsoftwig/twigcs#51]
When called as `vendor/bin/twigcs lint  app/Resources/views/`
The console report (and others) outputs filenames as `app/Resources/views//Path/tpl.html.twig` -- note the '**//**' in the filepath.

**Comment by OwlyCode** [comment]
Hello,

Thanks for reporting this. I'll add this issue to my list of things to fix. If anyone else wants to do it, feel free to ping me here.

**Comment by OwlyCode** [comment]
Fixed !
