### ISSUE TITLE
Add JUnit reporter

### ISSUE THREAD

**Issue by Chi-teck** [friendsoftwig/twigcs#54]
It would be helpful to have such a reporter when the sniffer is running in CI.

**Comment by OwlyCode** [comment]
Hello !

It is already a feature :smiley: 

```
twigcs /path/to/views --reporter checkstyle > /path/to/report.xml
```

**Comment by OwlyCode** [comment]
I completely forgot to mention that the reporter we provided for CI is using the checkstyle format (http://checkstyle.sourceforge.net/). 

I don't think JUnit would be a good fit for checkstyle results as it was made for test results.

**Comment by Chi-teck** [comment]
JUnit works well for other code sniffers. _phpcs_ and _eslint_ support it out of box. And _stylelint_ has a third-party package for it.

**Comment by OwlyCode** [comment]
Oh, I didn't realize that. Well I think we can come up with something for JUnit. Would you like to do it ?

**Comment by Chi-teck** [comment]
I can provide a PR for this later if nobody implements this before.

**Comment by Chi-teck** [comment]
Here is how it's done in PHP Code sniffer.
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Reports/Junit.php
