### ISSUE TITLE
Array rule

### ISSUE THREAD

**Issue by nlemoine** [friendsoftwig/twigcs#56]
Hi, 

In a Twig template, I have something like: 
```twig
{% for item in ['one', 'two'] if attribute(_context, item)) is not empty %}
{% endfor %}
```
Twigcs complains: `ERROR There should be no space after "]".`

But I think nothing's wrong is this syntax?

**Comment by OwlyCode** [comment]
Hello there, I'm sorry you didn't get an answer sooner. It is indeed a bug and I'll look into it soon. My time for open source projects is almost null at the moment. :disappointed:

**Comment by nlemoine** [comment]
No problem 😉

**Comment by OwlyCode** [comment]
This is on master, and scheduled for next beta version.
