### ISSUE TITLE
Twig 1 Support

### ISSUE THREAD

**Issue by builditzach** [friendsoftwig/twigcs#59]
Reopening issue: https://github.com/allocine/twigcs/issues/43

I am using twig 1.38.4 and twigcs v3.1.3.

I am not sure if it is related, but Twig recently did a major update to their namespaces: https://github.com/twigphp/Twig/commit/baa70287f5b8eff6d90c5779f82088379ebf94a4

**Comment by erik-seifert** [comment]
Same by me.
