### ISSUE TITLE
Does not respect both include syntaxes

### ISSUE THREAD

**Issue by kristiaanvandeneynde** [friendsoftwig/twigcs#60]
This is a follow-up to #49 

---

While the twigcs now correctly allows the following code to pass:
```
{% set foo %}1{% endset %}{{ include("foo.html.twig", {foo: foo}) }}
```
Valid as per: https://twig.symfony.com/doc/2.x/functions/include.html

It does not support:
```
{% set foo %}1{% endset %}{% include "foo.html.twig" with {foo: foo} %}
```
Valid as per: https://twig.symfony.com/doc/2.x/tags/include.html

---

The latter include tag is more popular in certain projects as the include function is then only called when trying to assign the inclusion result to a variable. When trying to output the include result, the tag syntax is preferred.

So please support both syntaxes as they are both valid.

You can add these lines to FunctionalTest.php:150 to check for the failure:
```
['{% set foo %}1{% endset %}{% include "foo.html.twig" with {foo: foo} %}', null],
['{% set foo %}1{% endset %}{% include "foo.html.twig" with {foo: foo} only %}', null],
```

**Comment by yguedidi** [comment]
I was about to report the same issue, but with:

```twig
{% include "foo.html.twig" with {foo: foo} only %}
```

(using `{%`, not `{{`)

**Comment by kristiaanvandeneynde** [comment]
My bad, the syntax for the tag method obviously uses `{%`

**Comment by OwlyCode** [comment]
This is on master, and scheduled for next beta version.
