### ISSUE TITLE
Support extended white space control operators in Twig templates

### ISSUE THREAD

**Issue by Chi-teck** [friendsoftwig/twigcs#62]
Those have been added recently.
https://github.com/twigphp/Twig/pull/2925

Example:
```
  {%~ if foo ~%}
Test
  {%~ endif ~%}
```
The above code produces the following Twigcs violations.
* ERROR There should be 1 space(s) after opening a block.
* ERROR There should be 1 space(s) before closing a block.
* ERROR There should be 1 space(s) before "~".
* ERROR There should be 1 space(s) after "~".
* ERROR There should be 1 space(s) after opening a block.
* ERROR There should be 1 space(s) before closing a block.
* ERROR There should be 1 space(s) before "~".
* ERROR There should be 1 space(s) after "~".

**Comment by OwlyCode** [comment]
This is on master, and scheduled for next beta version.
