### ISSUE TITLE
False positive no space before "("

### ISSUE THREAD

**Issue by yguedidi** [friendsoftwig/twigcs#63]
The following code gives a false positive:

```twig
{% block title ('page.title.' ~ type)|trans %}
```

The error: `ERROR There should be no space before "(".`

**Comment by OwlyCode** [comment]
Hello! Thank you for reporting this. I'm currently in the middle of a partial rewrite that should fix a lot of false positives for spacing.

**Comment by OwlyCode** [comment]
This is on master, and scheduled for next beta version.
