### ISSUE TITLE
False positive 1 space(s) after "-" with negative numbers

### ISSUE THREAD

**Issue by yguedidi** [friendsoftwig/twigcs#64]
The following code gives a false positive:

```twig
{% set sliced = and foo|slice(-12, 12) %}
```

The error: `ERROR There should be 1 space(s) after "-".`

**Comment by OwlyCode** [comment]
Hello! Thank you for reporting this. I'm currently in the middle of a partial rewrite that should fix a lot of false positives for spacing.

**Comment by OwlyCode** [comment]
This is on master, and scheduled for next beta version.

**Comment by truls1502** [comment]
@oallain, is it already in the `master`-branch? What is the commit number for the changes?

**Comment by oallain** [comment]
> @oallain, is it already in the `master`-branch? What is the commit number for the changes?

@truls1502  Sorry I don't understand your question, I haven't work on this issue.

**Comment by truls1502** [comment]
I am sorry, I tagged the wrong person. It was meant to @OwlyCode 😊

**Comment by oallain** [comment]
@truls1502 no problem ;)

So, i try it
With :
```twig
{% set sliced = and foo|slice(-12, 12) %}
```

friendsoftwig/twigcs:v3.1.3
> ERROR There should be 1 space(s) after "-".

friendsoftwig/twigcs:dev-master
No error :smile: 

To conclude, yes, it's good on master :+1:
