### ISSUE TITLE
Support "Forbidden functions" like PHPCs

### ISSUE THREAD

**Issue by PastisD** [friendsoftwig/twigcs#67]
Hello,

It can be usefull to add the ability to forbid some functions like [PHPCS](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericphpforbiddenfunctions).
It can avoid to push some debuggig function on GIT (Like "dump()") :P

**Comment by OwlyCode** [comment]
Hello,

Great idea! Please feel free to contribute it if you want, that would help us a lot! I'm currently fixing all the reported bugs.
