### ISSUE TITLE
Arrow functions

### ISSUE THREAD

**Issue by nlemoine** [friendsoftwig/twigcs#69]
Hi!

Twig recently introduced some array methods that uses arrow functions:
https://twig.symfony.com/doc/2.x/filters/column.html
https://twig.symfony.com/doc/2.x/filters/filter.html
https://twig.symfony.com/doc/2.x/filters/map.html
https://twig.symfony.com/doc/2.x/filters/reduce.html

Twigcs reports errors on this new syntax.

**Comment by nicwortel** [comment]
I get the following error when using Twigcs on a template containing an arrow function:

> ERROR There should be 1 space(s) before ">".

(using version 3.1.3)

**Comment by OwlyCode** [comment]
Hey there,

Arrow functions are not supported at the moment, I'm stuck in a longer-than-expected-should-have-shipped-sooner upgrade of the engine to address some issues that I couldn't solve with the old algorithms. (see #66)

As soon as I'm done I will upgrade the linter to handle all the new stuff that were added to twig in the meantime. I hope this will be done by the end of the year (I've been busy as a bee those past months...)
