### ISSUE TITLE
Error on master (erroneous comma)

### ISSUE THREAD

**Issue by SeenNotHurd** [friendsoftwig/twigcs#71]
Using master for a project, getting this:

`Parse error: syntax error, unexpected ')' in /Users/thomas/sites/theme/app/web/app/themes/pixels-starter-theme/vendor/friendsoftwig/twigcs/src/Rule/RegEngineRule.php on line 98`

Line 97 has a comma at the end that isn't needed :)

**Comment by OwlyCode** [comment]
Hi,

I just checked, I'm using php 7.3 which allows trailing comma for arguments, but this package must work with php 7.0. I'll push a quick fix in a minute.

**Comment by OwlyCode** [comment]
This should be fixed by now, let me know if you find other inconsistencies!
