### ISSUE TITLE
New optional parameter: excluded directories

### ISSUE THREAD

**Issue by mxr576** [friendsoftwig/twigcs#74]
Allow excluding directories (like: .git, .npm, etc.) from file scanning with a new optional parameter.

https://github.com/friendsoftwig/twigcs/blob/v3.1.3/src/Console/LintCommand.php#L37-L38

**Comment by OwlyCode** [comment]
Good idea!

**Comment by drupol** [comment]
This would also be very helpful for using TwigCS in [phpro/Grumphp](https://github.com/phpro/grumphp).
