### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by truls1502** [friendsoftwig/twigcs#82]
I was wondering if it is possible with a new release soon with [this changes](https://github.com/friendsoftwig/twigcs/compare/v3.1.3...master)?

**Comment by OwlyCode** [comment]
Hello,

I'm so sorry for the long wait. I still need #75 to get merged before we can release a  `v4-beta`. It lacks documentation on how to upgrade from v3.

**Comment by truls1502** [comment]
Could we create a list of what is needed to fix before releasing a beta version? It will make easier for us other contributors to help you and speed up the release timeframe! 🤓

**Comment by OwlyCode** [comment]
I did some cleanup by closing the issues that are fixed on master and yet to be released. Also, here's a label containing what issues should be closed for the next version : https://github.com/friendsoftwig/twigcs/issues?q=is%3Aissue+is%3Aopen+label%3A%22next+release%22

Thank you for help :smiley: !

**Comment by truls1502** [comment]
Maybe we could use milestone instead of a label from GitHub? In this way, the maintainers can easier put the issue to specific milestone/release number. And easier to see which one was related to the version. What do you think? 😊

**Comment by OwlyCode** [comment]
Oh yes I never used them before. That's better: https://github.com/friendsoftwig/twigcs/milestone/1

**Comment by OwlyCode** [comment]
I'm pleased to announce you that the beta is now available for public testing! https://github.com/friendsoftwig/twigcs/releases/tag/v4.0-BETA

So I'm closing this one, please open an issue if you encounter any problem :smiley:
